/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iaapp;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.lang.*;

/**
 *
 * @author praty
 */
public class OrderForm extends javax.swing.JFrame {
Connection conn=null;
    PreparedStatement pst=null;
    int rst;
    String Role;
    public OrderForm() {
        initComponents();
         conn=MySQLConnect.ConnectDB();
    }
    OrderForm(String role)
{
    initComponents();
    Role=role;
    conn=MySQLConnect.ConnectDB();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAddOrder = new javax.swing.JButton();
        lblEstDeliveryDt = new javax.swing.JLabel();
        dtEstDelivery = new com.toedter.calendar.JDateChooser();
        lblOrderDt = new javax.swing.JLabel();
        dtOrder = new com.toedter.calendar.JDateChooser();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblordertype3 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        lblordertype2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        lblCustomerID = new javax.swing.JLabel();
        txtcustomerID = new javax.swing.JTextField();
        lblordertype = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblordertype1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Order Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAddOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddOrder.setText("Add Order");
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });

        lblEstDeliveryDt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblEstDeliveryDt.setText("Select Estimated Delivery Date:");

        dtEstDelivery.setDateFormatString("yyyy-MM-dd");

        lblOrderDt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblOrderDt.setText("Select Order Date:");

        dtOrder.setDateFormatString("yyyy-MM-dd");

        lblAmount.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblAmount.setText("Enter Amount:");

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        lblQuantity.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblQuantity.setText("Enter Quantity:");

        lblordertype3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblordertype3.setText("Select Size:");

        jComboBox4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[SELECT]", "S", "M", "L", "XL", "XXL" }));

        lblordertype2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblordertype2.setText("Select Colour:");

        jComboBox3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[SELECT]", "Black", "White", "Royal Blue", "Red", "Green", "Orange", "Navy Blue", "Sky Blue", "Yellow", "Sea Green", "Maroon ", "Grey" }));

        lblCustomerID.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblCustomerID.setText("Enter Customer ID:");

        txtcustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomerIDActionPerformed(evt);
            }
        });

        lblordertype.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblordertype.setText("Select Item Type:");

        jComboBox1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[SELECT]", "Round Neck T-Shirt", "Polo T-Shirt", "SweatShirt", "Hoodie" }));

        lblordertype1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblordertype1.setText("Select Fabric:");

        jComboBox2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[SELECT]", "Dot Knit", "Cotton", "Fleece", "Superpoly" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCustomerID)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblordertype1)
                            .addComponent(lblordertype)
                            .addComponent(lblordertype2)
                            .addComponent(lblordertype3)
                            .addComponent(lblQuantity)
                            .addComponent(lblAmount)))
                    .addComponent(lblEstDeliveryDt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrderDt)
                        .addGap(11, 11, 11)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtEstDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnAddOrder)
                .addGap(92, 92, 92)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerID)
                    .addComponent(txtcustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblordertype)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblordertype1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblordertype2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblordertype3)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrderDt)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstDeliveryDt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dtEstDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddOrder)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
        if(txtcustomerID.getText().isEmpty() || txtQuantity.getText().isEmpty() || txtAmount.getText().isEmpty() || dtOrder.getDate().toString().isEmpty()  || dtEstDelivery.getDate().toString().isEmpty() )
        {
            JOptionPane.showMessageDialog(this, "Please fill in all Details!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String type,fabric,colour,size;

            boolean check=false;
            type=jComboBox1.getSelectedItem().toString();
            fabric=jComboBox2.getSelectedItem().toString();
            colour=jComboBox3.getSelectedItem().toString();
            size=jComboBox4.getSelectedItem().toString();
            if(type=="[SELECT]"||fabric=="[SELECT]"||colour=="[SELECT]"||size=="[SELECT]")
            JOptionPane.showMessageDialog(null, "****Invalid Selection!!****");
            else{
                int Item_ID,Quantity;
                try{
                    String sql2="select Item_ID, Quantity from inventory where Item_Type= '"+type+"' and Fabric= '"+fabric+"' and Color= '"+colour+"' and Size= '"+size+"'";
                    pst=conn.prepareStatement(sql2);
                    ResultSet rs=(ResultSet) pst.executeQuery();
                    while(rs.next())
                    {
                        check=true;
                        Item_ID=rs.getInt("Item_ID");
                        Quantity=rs.getInt("Quantity");
                        if(Quantity>=Integer.parseInt(txtQuantity.getText()))
                        {
                            String sql3="update inventory set Quantity= "+Quantity+"-"+txtQuantity.getText()+" where Item_ID= "+Item_ID;
                            pst=conn.prepareStatement(sql3);
                            pst.executeUpdate();
                            String Sql="insert into orders values (?,?,?,?,?,?,?,?,?,?)";//Question marks represent columns in the database
                            try{
                                pst = conn.prepareStatement(Sql);
                                pst.setInt(1,0);
                                //pst.setString(2, this.txtcustomerID.getText());
                                pst.setString(2,txtcustomerID.getText());
                                pst.setInt(3,Item_ID);
                                pst.setInt(4,Integer.parseInt(txtQuantity.getText()));
                                pst.setString(5,((JTextField)dtOrder.getDateEditor().getUiComponent()).getText());
                                pst.setString(6,((JTextField)dtEstDelivery.getDateEditor().getUiComponent()).getText());
                                pst.setString(7,null);
                                pst.setInt(8,Integer.parseInt(txtAmount.getText()));
                                pst.setInt(9,Integer.parseInt(txtAmount.getText()));
                                pst.setString(10,"pending");
                                int i = pst.executeUpdate();
                                if(i>0){

                                    JOptionPane.showMessageDialog(null, "Order Made Successfully");//Confirmation that data is stored in the database
                                    int CustomerID=Integer.parseInt(txtcustomerID.getText());
                                    String name="";
                                    String email="";
                                    String contact="";
                                    String OrderQuantity=txtQuantity.getText();
                                    String OrderDate=((JTextField)dtOrder.getDateEditor().getUiComponent()).getText();
                                    String Amount=txtAmount.getText();
                                    String ReceiptQuery="select Customer_Name,Email_ID,Contact_NO from customers where Customer_ID="+CustomerID;
                                    pst=conn.prepareStatement(ReceiptQuery);
                                    ResultSet rs1=(ResultSet) pst.executeQuery();
                                    while(rs1.next())
                                    {
                                        name=rs1.getString(1);
                                        email=rs1.getString(2);
                                        contact=rs1.getString(3);
                                    }
                                    new OrderReceipt(name,email,contact,colour,fabric,type,size,OrderQuantity,OrderDate,Amount,Role).setVisible(true);
                                    this.dispose();
                                }
                                else{
                                    JOptionPane.showMessageDialog(null,"Order Not Made");//Notice that data is not saved in the database
                                }
                            }
                            //catch(HeadlessException | SQLException e){
                                catch(SQLException e){
                                    JOptionPane.showMessageDialog(null, e);
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "Insufficient Quantity! Reorder Some?");
                                ReorderForm reorder= new ReorderForm();
                                reorder.setVisible(true);//Directs user to the Reorder Form
                                setVisible(false);
                            }
                        }
                        if(check==false)
                        {
                            String sql4="insert into inventory values (?,?,?,?,?,?,?)";
                            pst=conn.prepareStatement(sql4);
                            pst.setInt(1,0);
                            pst.setString(2,type);
                            pst.setString(3, fabric);
                            pst.setString(4,colour);
                            pst.setString(5,size);
                            pst.setInt(6,0);
                            pst.setString(7,null);
                            int j=pst.executeUpdate();
                            if(j>0)
                            {
                                JOptionPane.showMessageDialog(null, "Insufficient Quantity! Reorder Some?");
                                ReorderForm reorder= new ReorderForm(Role);
                                reorder.setVisible(true);//Directs user to the Reorder Form
                                setVisible(false);
                            }

                        }
                    }

                    catch(SQLException e){
                        JOptionPane.showMessageDialog(null, e);
                    }

                }
            }

    }//GEN-LAST:event_btnAddOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Orders ords= new Orders(Role);
        ords.setVisible(true);//Displays the Customer Form
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtcustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomerIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private com.toedter.calendar.JDateChooser dtEstDelivery;
    private com.toedter.calendar.JDateChooser dtOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblEstDeliveryDt;
    private javax.swing.JLabel lblOrderDt;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblordertype;
    private javax.swing.JLabel lblordertype1;
    private javax.swing.JLabel lblordertype2;
    private javax.swing.JLabel lblordertype3;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtcustomerID;
    // End of variables declaration//GEN-END:variables

  

        private static int parseInt(String text) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        

        
    
}
