/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iaapp;
import com.toedter.calendar.JDateChooser;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import net.proteanit.sql.DbUtils;
import java.text.*;
import java.awt.PrintGraphics.*;
import javax.swing.JTable;
/**
 *
 * @author praty
 */
public class ViewOrders extends javax.swing.JFrame {
Connection conn=null;
    PreparedStatement pst=null;
    String Role;
    int rst;
    /**
     * Creates new form ViewOrders
     */
    public ViewOrders() {
        initComponents();
        conn=MySQLConnect.ConnectDB();
        DisplayOrders();
    }
    ViewOrders(String role)
{
    initComponents();
    Role=role;
    conn=MySQLConnect.ConnectDB();
        DisplayOrders();
}
public void DisplayOrders()
{
    try{
    String query="select * from orders";
        pst=conn.prepareStatement(query);
        ResultSet rs=(ResultSet) pst.executeQuery();
        tblOrders.setModel(DbUtils.resultSetToTableModel(rs));
    
}
catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    MyPanel.hide();

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lblOrderID = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblOrderType = new javax.swing.JLabel();
        lblOrderDate = new javax.swing.JLabel();
        lblEstmDate = new javax.swing.JLabel();
        lblAmt = new javax.swing.JLabel();
        lblDue = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MyPanel = new javax.swing.JDesktopPane();
        btnpenamt = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(519, 519, 519)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order_ID", "Customer_ID", "Quantity", "Order_type", "Order_Date", "Date_Estimated", "Completion_Date", "Total_Amount", "Amount_Pending", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton1.setText("Search/Filter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblOrderID.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblOrderID.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderID.setText("Order ID:");

        lblCustomerName.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerName.setText("Customer Name:");

        lblQuantity.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity.setText("Quantity:");

        lblOrderType.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblOrderType.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderType.setText("Order Type:");

        lblOrderDate.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblOrderDate.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderDate.setText("Order Date:");

        lblEstmDate.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblEstmDate.setForeground(new java.awt.Color(255, 255, 255));
        lblEstmDate.setText("Estimated Date:");

        lblAmt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblAmt.setForeground(new java.awt.Color(255, 255, 255));
        lblAmt.setText("Amount:");

        lblDue.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblDue.setForeground(new java.awt.Color(255, 255, 255));
        lblDue.setText("Due:");

        lblStatus.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Status:");

        MyPanel.setBackground(new java.awt.Color(0, 0, 0));

        btnpenamt.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        btnpenamt.setText("Update Pending Amount");
        btnpenamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpenamtActionPerformed(evt);
            }
        });

        btnStatus.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        btnStatus.setText("Update Status");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });

        MyPanel.setLayer(btnpenamt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MyPanel.setLayer(btnStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MyPanelLayout = new javax.swing.GroupLayout(MyPanel);
        MyPanel.setLayout(MyPanelLayout);
        MyPanelLayout.setHorizontalGroup(
            MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnpenamt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        MyPanelLayout.setVerticalGroup(
            MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpenamt)
                    .addComponent(btnStatus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyPanel)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(MyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(0, 204, 51));
        jButton3.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton2.setText("Generate PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblCustomerName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblQuantity, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblOrderType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblOrderDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblEstmDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblAmt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblDue, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderID)
                            .addComponent(lblQuantity)
                            .addComponent(lblAmt))
                        .addGap(140, 140, 140)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDue)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCustomerName)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addComponent(jButton2)))
                                .addGap(107, 107, 107)
                                .addComponent(jButton1))
                            .addComponent(lblOrderDate)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(422, 422, 422)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEstmDate)
                                    .addComponent(lblOrderType)
                                    .addComponent(lblStatus)))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(63, 63, 63)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID)
                    .addComponent(lblCustomerName)
                    .addComponent(lblOrderType))
                .addGap(29, 29, 29)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(lblOrderDate)
                    .addComponent(lblEstmDate))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmt)
                    .addComponent(lblDue)
                    .addComponent(lblStatus))
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String option[]={"[SELECT]","Order ID","Customer ID","Order Date","Status"};
 JComboBox cb=new JComboBox(option);
 int input;
 input=JOptionPane.showConfirmDialog(this,cb,"SELECT CATEGORY",JOptionPane.DEFAULT_OPTION);
 if(input==JOptionPane.OK_OPTION)
 {
     String choice=(String)cb.getSelectedItem();
     if("[SELECT]".equals(choice))
     JOptionPane.showMessageDialog(this, "**Select a Category!!**");
     else if (choice.equals("Order ID"))
     {
         try{
         String OrderID=JOptionPane.showInputDialog(this,"Enter Order ID");
         String query = "select * from orders where Order_ID="+OrderID;
         pst=conn.prepareStatement(query);
         ResultSet rs=pst.executeQuery();
         tblOrders.setModel(DbUtils.resultSetToTableModel(rs));
         }
         catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
     }
     else if(choice.equals("Customer ID")){
         try{
         String CustomerID=JOptionPane.showInputDialog(this,"Enter Customer ID");
         String query = "select * from orders where Customer_ID="+CustomerID;
         pst=conn.prepareStatement(query);
         ResultSet rs=pst.executeQuery();
         tblOrders.setModel(DbUtils.resultSetToTableModel(rs));
         }
         catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);} }
     else if(choice.equals("Status"))
     {
         String status[]={"[SELECT]","pending","complete"};
         JComboBox cb2=new JComboBox(status);
         int input2=JOptionPane.showConfirmDialog(this,cb2,"SELECT STATUS",JOptionPane.DEFAULT_OPTION);
         if(input==JOptionPane.OK_OPTION)
         {
             String choice2=(String)cb2.getSelectedItem();
             if("[SELECT]".equals(choice2))
             JOptionPane.showMessageDialog(this, "**Select a Category!!**");
             else{
                 try{
         String query = "select * from orders where Order_Status='"+choice2+"'";
         pst=conn.prepareStatement(query);
         ResultSet rs=pst.executeQuery();
         tblOrders.setModel(DbUtils.resultSetToTableModel(rs));
         }
         catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }

             }
         }
     }
     else
     {
         JDateChooser startdate=new JDateChooser();//code received from https://stackoverflow.com/questions/35347519/display-jdatechooser-in-joptionpane#:~:text=JDateChooser%20jd%20%3D%20new%20JDateChooser()%3B,JOptionPane%20I%20implemented%20a%20SimpleDateFormat.
         String message ="Choose start date:\n";
         Object[] SDateparams={message,startdate};
         JOptionPane.showConfirmDialog(null,SDateparams,"Start date", JOptionPane.PLAIN_MESSAGE);
         String sdateinput="";
         SimpleDateFormat sdf=new SimpleDateFormat("YYYY-MM-dd");
         sdateinput=sdf.format(((JDateChooser)SDateparams[1]).getDate());
         
         JDateChooser enddate=new JDateChooser();
         message="Choose end date:\n";
         Object [] EDateparams={message,enddate};
         JOptionPane.showConfirmDialog(null,EDateparams,"End date", JOptionPane.PLAIN_MESSAGE);
         String edateinput="";
         edateinput=sdf.format(((JDateChooser)EDateparams[1]).getDate());
         try{
        
        String query="select * from orders where Order_Date between '"+sdateinput+"' and '"+edateinput+"'";
        pst=conn.prepareStatement(query);
        ResultSet rs=(ResultSet) pst.executeQuery();
        tblOrders.setModel(DbUtils.resultSetToTableModel(rs));
    }                                         
    catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
     }
     
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnpenamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpenamtActionPerformed
int row=tblOrders.getSelectedRow();
String penamt=JOptionPane.showInputDialog(this, "Enter New Pending Amount");
try{
        
        String query="update orders set Amount_Pending="+penamt+" where Order_ID="+tblOrders.getModel().getValueAt(row, 0).toString();
        pst=conn.prepareStatement(query);
        int i=pst.executeUpdate();
        if(i>0)
        {
            JOptionPane.showMessageDialog(null,"Pending Amount updated successfully!" );
            new ViewOrders().setVisible(true);
            this.dispose();
        }
        
    }                                         
    catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnpenamtActionPerformed

    private void tblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdersMouseClicked
int row=tblOrders.getSelectedRow();
            lblOrderID.setText("Order ID: "+tblOrders.getModel().getValueAt(row, 0).toString());
            try{
        
        String query="select Customer_Name from customers where Customer_ID="+tblOrders.getModel().getValueAt(row, 1).toString();
        pst=conn.prepareStatement(query);
        ResultSet rs=(ResultSet) pst.executeQuery();
        if(rs.next())
        lblCustomerName.setText("Customer Name: "+rs.getString(1));
    }                                         
    catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
            lblOrderType.setText("Order Type: "+tblOrders.getModel().getValueAt(row, 3).toString());
            lblQuantity.setText("Quantity: "+tblOrders.getModel().getValueAt(row, 2).toString());
            lblOrderDate.setText("Order Date: "+tblOrders.getModel().getValueAt(row, 4).toString());      
            lblEstmDate.setText("Estimated Date: "+tblOrders.getModel().getValueAt(row, 5).toString());
            lblAmt.setText("Amount: "+tblOrders.getModel().getValueAt(row, 7).toString());
            lblDue.setText("Due: "+tblOrders.getModel().getValueAt(row, 8).toString());
            lblStatus.setText("Status: "+tblOrders.getModel().getValueAt(row, 9).toString());
            if(tblOrders.getModel().getValueAt(row,9).toString().equals("pending"))
            MyPanel.show();
            else
            MyPanel.hide();
    }//GEN-LAST:event_tblOrdersMouseClicked

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
      int row=tblOrders.getSelectedRow();
       try{
        
        String query="select Amount_Pending from orders where Order_ID="+tblOrders.getModel().getValueAt(row, 0).toString();
        
        pst=conn.prepareStatement(query);
        ResultSet rs=(ResultSet) pst.executeQuery();
        if(rs.next())
        {
            if(rs.getString(1).equals("0"))
            {
                JDateChooser completionDate=new JDateChooser();
         String message ="Choose Order Completion Date:\n";
         Object[] SDateparams={message,completionDate};
         JOptionPane.showConfirmDialog(null,SDateparams,"Completion date", JOptionPane.PLAIN_MESSAGE);
         String compdateinput="";
         SimpleDateFormat sdf=new SimpleDateFormat("YYYY-MM-dd");
         compdateinput=sdf.format(((JDateChooser)SDateparams[1]).getDate());
         String query2="update orders set Order_Status='complete', Completion_Date='"+compdateinput+"' where Order_ID="+tblOrders.getModel().getValueAt(row, 0).toString();
         System.out.print(query2);
        pst=conn.prepareStatement(query2);
        int i=pst.executeUpdate();
        if(i>0)
        {
            JOptionPane.showMessageDialog(null,"Status updated successfully!" );
            new ViewOrders().setVisible(true);
            this.dispose();
        }
            }
            else
            JOptionPane.showMessageDialog(null, "**Please clear the Order's Pending amount first!**");
        }
    }                                         
    catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnStatusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Orders ords= new Orders(Role);
          ords.setVisible(true);//Displays the Orders interface
          this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
MessageFormat header=new MessageFormat("Order Report");
MessageFormat footer=new MessageFormat("Labket Technologies Pvt Ltd");
        try{
    tblOrders.print(JTable.PrintMode.FIT_WIDTH, header, footer);
}
  catch(java.awt.print.PrinterException e){
      System.err.format("Cannot print %s%n",e.getMessage());
  }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MyPanel;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnpenamt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmt;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDue;
    private javax.swing.JLabel lblEstmDate;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblOrderType;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
}
